//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class combos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal combos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.combos", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Articles.
        /// </summary>
        internal static string eAcknowledgementsub_articles {
            get {
                return ResourceManager.GetString("eAcknowledgementsub_articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Both.
        /// </summary>
        internal static string eAcknowledgementsub_both {
            get {
                return ResourceManager.GetString("eAcknowledgementsub_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Select.
        /// </summary>
        internal static string eAcknowledgementsub_noselect {
            get {
                return ResourceManager.GetString("eAcknowledgementsub_noselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        internal static string eAcknowledgementsub_other {
            get {
                return ResourceManager.GetString("eAcknowledgementsub_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pictures.
        /// </summary>
        internal static string eAcknowledgementsub_pictures {
            get {
                return ResourceManager.GetString("eAcknowledgementsub_pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Select.
        /// </summary>
        internal static string eAgreetment_noselect {
            get {
                return ResourceManager.GetString("eAgreetment_noselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organitatiton.
        /// </summary>
        internal static string eAgreetment_organitatiton {
            get {
                return ResourceManager.GetString("eAgreetment_organitatiton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        internal static string eAgreetment_other {
            get {
                return ResourceManager.GetString("eAgreetment_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a People.
        /// </summary>
        internal static string eAgreetment_people {
            get {
                return ResourceManager.GetString("eAgreetment_people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Africa.
        /// </summary>
        internal static string eContinent_africa {
            get {
                return ResourceManager.GetString("eContinent_africa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a America North.
        /// </summary>
        internal static string eContinent_america_north {
            get {
                return ResourceManager.GetString("eContinent_america_north", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a America South.
        /// </summary>
        internal static string eContinent_america_south {
            get {
                return ResourceManager.GetString("eContinent_america_south", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asia east.
        /// </summary>
        internal static string eContinent_asia_east {
            get {
                return ResourceManager.GetString("eContinent_asia_east", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asia oest.
        /// </summary>
        internal static string eContinent_asia_oest {
            get {
                return ResourceManager.GetString("eContinent_asia_oest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Australia.
        /// </summary>
        internal static string eContinent_australia {
            get {
                return ResourceManager.GetString("eContinent_australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Europe.
        /// </summary>
        internal static string eContinent_europe {
            get {
                return ResourceManager.GetString("eContinent_europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocean.
        /// </summary>
        internal static string eContinent_ocean {
            get {
                return ResourceManager.GetString("eContinent_ocean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remote Island.
        /// </summary>
        internal static string eContinent_remote_islands {
            get {
                return ResourceManager.GetString("eContinent_remote_islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anathomy.
        /// </summary>
        internal static string E_AppendixesTypeSub_anathomy {
            get {
                return ResourceManager.GetString("E_AppendixesTypeSub_anathomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Botanic.
        /// </summary>
        internal static string E_AppendixesTypeSub_botanic {
            get {
                return ResourceManager.GetString("E_AppendixesTypeSub_botanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chemist.
        /// </summary>
        internal static string E_AppendixesTypeSub_chemist {
            get {
                return ResourceManager.GetString("E_AppendixesTypeSub_chemist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ecology.
        /// </summary>
        internal static string E_AppendixesTypeSub_ecology {
            get {
                return ResourceManager.GetString("E_AppendixesTypeSub_ecology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ethimology.
        /// </summary>
        internal static string E_AppendixesTypeSub_ethimology {
            get {
                return ResourceManager.GetString("E_AppendixesTypeSub_ethimology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        internal static string E_AppendixesTypeSub_other {
            get {
                return ResourceManager.GetString("E_AppendixesTypeSub_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoology.
        /// </summary>
        internal static string E_AppendixesTypeSub_zoology {
            get {
                return ResourceManager.GetString("E_AppendixesTypeSub_zoology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Biology.
        /// </summary>
        internal static string E_AppendixesType_biology {
            get {
                return ResourceManager.GetString("E_AppendixesType_biology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Botanic.
        /// </summary>
        internal static string E_AppendixesType_botanic {
            get {
                return ResourceManager.GetString("E_AppendixesType_botanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chemist.
        /// </summary>
        internal static string E_AppendixesType_chemist {
            get {
                return ResourceManager.GetString("E_AppendixesType_chemist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ecology.
        /// </summary>
        internal static string E_AppendixesType_ecology {
            get {
                return ResourceManager.GetString("E_AppendixesType_ecology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ethimology.
        /// </summary>
        internal static string E_AppendixesType_ethimology {
            get {
                return ResourceManager.GetString("E_AppendixesType_ethimology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No select.
        /// </summary>
        internal static string E_AppendixesType_noselect {
            get {
                return ResourceManager.GetString("E_AppendixesType_noselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        internal static string E_AppendixesType_other {
            get {
                return ResourceManager.GetString("E_AppendixesType_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoology.
        /// </summary>
        internal static string E_AppendixesType_zoology {
            get {
                return ResourceManager.GetString("E_AppendixesType_zoology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a basic.
        /// </summary>
        internal static string E_ArticleTypesub_basic {
            get {
                return ResourceManager.GetString("E_ArticleTypesub_basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a expert.
        /// </summary>
        internal static string E_ArticleTypesub_expert {
            get {
                return ResourceManager.GetString("E_ArticleTypesub_expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hight recomendable.
        /// </summary>
        internal static string E_ArticleTypesub_hightrecomendable {
            get {
                return ResourceManager.GetString("E_ArticleTypesub_hightrecomendable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        internal static string E_ArticleTypesub_other {
            get {
                return ResourceManager.GetString("E_ArticleTypesub_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Art and Society.
        /// </summary>
        internal static string E_ArticleType_art_society {
            get {
                return ResourceManager.GetString("E_ArticleType_art_society", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Biology.
        /// </summary>
        internal static string E_ArticleType_biology {
            get {
                return ResourceManager.GetString("E_ArticleType_biology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Care Sheet.
        /// </summary>
        internal static string E_ArticleType_caresheet {
            get {
                return ResourceManager.GetString("E_ArticleType_caresheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conservancy project.
        /// </summary>
        internal static string E_ArticleType_conservancy_project {
            get {
                return ResourceManager.GetString("E_ArticleType_conservancy_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseases.
        /// </summary>
        internal static string E_ArticleType_diseases {
            get {
                return ResourceManager.GetString("E_ArticleType_diseases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foods.
        /// </summary>
        internal static string E_ArticleType_foods {
            get {
                return ResourceManager.GetString("E_ArticleType_foods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Others.
        /// </summary>
        internal static string E_ArticleType_other {
            get {
                return ResourceManager.GetString("E_ArticleType_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a People.
        /// </summary>
        internal static string E_ArticleType_people {
            get {
                return ResourceManager.GetString("E_ArticleType_people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tools.
        /// </summary>
        internal static string E_ArticleType_tools {
            get {
                return ResourceManager.GetString("E_ArticleType_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a people.
        /// </summary>
        internal static string E_ArticleType_vocabulary {
            get {
                return ResourceManager.GetString("E_ArticleType_vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ecozone.
        /// </summary>
        internal static string E_EcozoneTypesub_ecozone {
            get {
                return ResourceManager.GetString("E_EcozoneTypesub_ecozone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string E_EcozoneType_description {
            get {
                return ResourceManager.GetString("E_EcozoneType_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bad.
        /// </summary>
        internal static string E_FoodTypeSub_bad {
            get {
                return ResourceManager.GetString("E_FoodTypeSub_bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Good.
        /// </summary>
        internal static string E_FoodTypeSub_good {
            get {
                return ResourceManager.GetString("E_FoodTypeSub_good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        internal static string E_FoodTypeSub_other {
            get {
                return ResourceManager.GetString("E_FoodTypeSub_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prohibited.
        /// </summary>
        internal static string E_FoodTypeSub_prohibited {
            get {
                return ResourceManager.GetString("E_FoodTypeSub_prohibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Very good.
        /// </summary>
        internal static string E_FoodTypeSub_very_good {
            get {
                return ResourceManager.GetString("E_FoodTypeSub_very_good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Occasionally.
        /// </summary>
        internal static string E_FoodTypeSub_very_occasionally {
            get {
                return ResourceManager.GetString("E_FoodTypeSub_very_occasionally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animal.
        /// </summary>
        internal static string E_FoodType_animal {
            get {
                return ResourceManager.GetString("E_FoodType_animal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manufactured.
        /// </summary>
        internal static string E_FoodType_manufactured {
            get {
                return ResourceManager.GetString("E_FoodType_manufactured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medicines.
        /// </summary>
        internal static string E_FoodType_medicines {
            get {
                return ResourceManager.GetString("E_FoodType_medicines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        internal static string E_FoodType_other {
            get {
                return ResourceManager.GetString("E_FoodType_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supplements.
        /// </summary>
        internal static string E_FoodType_supplements {
            get {
                return ResourceManager.GetString("E_FoodType_supplements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vegetable.
        /// </summary>
        internal static string E_FoodType_vegetable {
            get {
                return ResourceManager.GetString("E_FoodType_vegetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Files.
        /// </summary>
        internal static string E_MediaGalTypeSub_files {
            get {
                return ResourceManager.GetString("E_MediaGalTypeSub_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Images.
        /// </summary>
        internal static string E_MediaGalType_Gallery {
            get {
                return ResourceManager.GetString("E_MediaGalType_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conservancy project.
        /// </summary>
        internal static string E_NoticeType_conservancy_project {
            get {
                return ResourceManager.GetString("E_NoticeType_conservancy_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Law.
        /// </summary>
        internal static string E_NoticeType_law {
            get {
                return ResourceManager.GetString("E_NoticeType_law", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Select.
        /// </summary>
        internal static string E_NoticeType_nolect {
            get {
                return ResourceManager.GetString("E_NoticeType_nolect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        internal static string E_NoticeType_other {
            get {
                return ResourceManager.GetString("E_NoticeType_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Society.
        /// </summary>
        internal static string E_NoticeType_society {
            get {
                return ResourceManager.GetString("E_NoticeType_society", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string E_NoticeType_specie {
            get {
                return ResourceManager.GetString("E_NoticeType_specie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description error.
        /// </summary>
        internal static string E_TaxonTypeSub_error {
            get {
                return ResourceManager.GetString("E_TaxonTypeSub_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extint recent.
        /// </summary>
        internal static string E_TaxonTypeSub_extinct {
            get {
                return ResourceManager.GetString("E_TaxonTypeSub_extinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extinct only fosils.
        /// </summary>
        internal static string E_TaxonTypeSub_extinct_fossil {
            get {
                return ResourceManager.GetString("E_TaxonTypeSub_extinct_fossil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extinct in wild.
        /// </summary>
        internal static string E_TaxonTypeSub_extinct_wild {
            get {
                return ResourceManager.GetString("E_TaxonTypeSub_extinct_wild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Live in wild.
        /// </summary>
        internal static string E_TaxonTypeSub_live {
            get {
                return ResourceManager.GetString("E_TaxonTypeSub_live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No select.
        /// </summary>
        internal static string E_TaxonTypeSub_noselect {
            get {
                return ResourceManager.GetString("E_TaxonTypeSub_noselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clase.
        /// </summary>
        internal static string E_TaxonType_class_ {
            get {
                return ResourceManager.GetString("E_TaxonType_class_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Family.
        /// </summary>
        internal static string E_TaxonType_family {
            get {
                return ResourceManager.GetString("E_TaxonType_family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Genus.
        /// </summary>
        internal static string E_TaxonType_genus {
            get {
                return ResourceManager.GetString("E_TaxonType_genus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No select.
        /// </summary>
        internal static string E_TaxonType_noselect {
            get {
                return ResourceManager.GetString("E_TaxonType_noselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Order.
        /// </summary>
        internal static string E_TaxonType_order {
            get {
                return ResourceManager.GetString("E_TaxonType_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Specie.
        /// </summary>
        internal static string E_TaxonType_specie {
            get {
                return ResourceManager.GetString("E_TaxonType_specie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subclase.
        /// </summary>
        internal static string E_TaxonType_subclass {
            get {
                return ResourceManager.GetString("E_TaxonType_subclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subfamily.
        /// </summary>
        internal static string E_TaxonType_subfamily {
            get {
                return ResourceManager.GetString("E_TaxonType_subfamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suborder.
        /// </summary>
        internal static string E_TaxonType_suborder {
            get {
                return ResourceManager.GetString("E_TaxonType_suborder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Superfamily.
        /// </summary>
        internal static string E_TaxonType_superfamily {
            get {
                return ResourceManager.GetString("E_TaxonType_superfamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hight.
        /// </summary>
        internal static string E_TodoTypesub_hight {
            get {
                return ResourceManager.GetString("E_TodoTypesub_hight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Low.
        /// </summary>
        internal static string E_TodoTypesub_low {
            get {
                return ResourceManager.GetString("E_TodoTypesub_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medium.
        /// </summary>
        internal static string E_TodoTypesub_medium {
            get {
                return ResourceManager.GetString("E_TodoTypesub_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No select.
        /// </summary>
        internal static string E_TodoTypesub_noselect {
            get {
                return ResourceManager.GetString("E_TodoTypesub_noselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nothing.
        /// </summary>
        internal static string E_TodoTypesub_nothing {
            get {
                return ResourceManager.GetString("E_TodoTypesub_nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string E_TodoType_cancel {
            get {
                return ResourceManager.GetString("E_TodoType_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doing.
        /// </summary>
        internal static string E_TodoType_doing {
            get {
                return ResourceManager.GetString("E_TodoType_doing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Done.
        /// </summary>
        internal static string E_TodoType_done {
            get {
                return ResourceManager.GetString("E_TodoType_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No select.
        /// </summary>
        internal static string E_TodoType_noselect {
            get {
                return ResourceManager.GetString("E_TodoType_noselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting.
        /// </summary>
        internal static string E_TodoType_waiting {
            get {
                return ResourceManager.GetString("E_TodoType_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Breader.
        /// </summary>
        internal static string referencetypesub_breader {
            get {
                return ResourceManager.GetString("referencetypesub_breader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cientific.
        /// </summary>
        internal static string referencetypesub_cientific {
            get {
                return ResourceManager.GetString("referencetypesub_cientific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conservation Group.
        /// </summary>
        internal static string referencetypesub_conservationgroup {
            get {
                return ResourceManager.GetString("referencetypesub_conservationgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Education.
        /// </summary>
        internal static string referencetypesub_education {
            get {
                return ResourceManager.GetString("referencetypesub_education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a goverment.
        /// </summary>
        internal static string referencetypesub_goverment {
            get {
                return ResourceManager.GetString("referencetypesub_goverment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        internal static string referencetypesub_other {
            get {
                return ResourceManager.GetString("referencetypesub_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoo.
        /// </summary>
        internal static string referencetypesub_zoo {
            get {
                return ResourceManager.GetString("referencetypesub_zoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrupation.
        /// </summary>
        internal static string referencetype_agrupation {
            get {
                return ResourceManager.GetString("referencetype_agrupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comerce.
        /// </summary>
        internal static string referencetype_comerce {
            get {
                return ResourceManager.GetString("referencetype_comerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Institution.
        /// </summary>
        internal static string referencetype_institution {
            get {
                return ResourceManager.GetString("referencetype_institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mutimedia.
        /// </summary>
        internal static string referencetype_mutimedia {
            get {
                return ResourceManager.GetString("referencetype_mutimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Natural reserve.
        /// </summary>
        internal static string referencetype_NaturalReserve {
            get {
                return ResourceManager.GetString("referencetype_NaturalReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        internal static string referencetype_other {
            get {
                return ResourceManager.GetString("referencetype_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a People.
        /// </summary>
        internal static string referencetype_people {
            get {
                return ResourceManager.GetString("referencetype_people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Publication.
        /// </summary>
        internal static string referencetype_publication {
            get {
                return ResourceManager.GetString("referencetype_publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Veterinary.
        /// </summary>
        internal static string referencetype_veterinary {
            get {
                return ResourceManager.GetString("referencetype_veterinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Website.
        /// </summary>
        internal static string referencetype_website {
            get {
                return ResourceManager.GetString("referencetype_website", resourceCulture);
            }
        }
    }
}
