//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testudines.cls
{
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClsTranslator
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCultureLeft;
        private static global::System.Globalization.CultureInfo resourceCultureRight;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClsTranslator(String pCultureLeft = "es-ES", String pCultureRight = "en-EN")
        {
            resourceCultureLeft = new global::System.Globalization.CultureInfo(pCultureLeft);
            resourceCultureRight = new global::System.Globalization.CultureInfo(pCultureRight);

        }

        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]

        public void fncSetCultures(String pCultureLeft = "es-ES", String pCultureRight = "en-EN")
        {
            resourceCultureLeft = new global::System.Globalization.CultureInfo(pCultureLeft);
            resourceCultureLeft = new global::System.Globalization.CultureInfo(pCultureRight);
        }
        //-------------------------------------------------------------------------------
        public void ind_Chapter01_00Abs(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter01_00Abs", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter01_00Abs Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter01_00Abs", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter01_00Abs Not found"; }
        }
        //---------------------------------------------------------------------------------

        //-------------------------------------------------------------------------------
        public void ind_Chapter01_01AbsDes(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter01_01AbsDes", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter01_01AbsDes Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter01_01AbsDes", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter01_01AbsDes Not found"; }
        }
        //---------------------------------------------------------------------------------
        //-------------------------------------------------------------------------------
        public void ind_Chapter01_02AbsNat(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter01_02AbsNat", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter01_02AbsNat Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter01_02AbsNat", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter01_02AbsNat Not found"; }
        }
        //---------------------------------------------------------------------------------
        //-------------------------------------------------------------------------------
        public void ind_Chapter01_03AbsRng(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter01_03AbsRng", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter01_03AbsRng Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter01_03AbsRng", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter01_03AbsRng Not found"; }
        }
        //---------------------------------------------------------------------------------

        //-------------------------------------------------------------------------------
        public void ind_Chapter01_04AbsTax(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter01_04AbsTax", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter01_04AbsTax Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter01_04AbsTax", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter01_04AbsTax Not found"; }
        }
        //---------------------------------------------------------------------------------
        public void ind_Chapter01_04AbsTax_subspecies(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter01_04AbsTax_subspecies", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter01_04AbsTax_subspecies Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter01_04AbsTax_subspecies", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter01_04AbsTax_subspecies Not found"; }
        }
        //---------------------------------------------------------------------------------

        public void ind_Chapter01_05AbsNear(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter01_05AbsNear", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter01_05AbsNear Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter01_05AbsNear", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter01_05AbsNear Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter01_06AbsGal(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter01_06AbsGal", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter01_06AbsGal Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter01_06AbsGal", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter01_06AbsGal Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter01_10absGalIntro(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter01_10absGalIntro", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter01_10absGalIntro Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter01_10absGalIntro", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter01_10absGalIntro Not found"; }
        }
        //---------------------------------------------------------------------------------

        public void ind_Chapter02_00description(ref String pLngLeft, ref String pLngRight)
        {
            //Resources.Strings.ind_Chapter02_00Des
            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_00Des", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_00Des Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_00Des", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_00Des Not found"; }
        }
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_01desAbs(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_01desAbs", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_01desAbs Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_01desAbs", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_01desAbs Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_02DesDors(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_02DesDors", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_02DesDors Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_02DesDors", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_02DesDors Not found"; }
        }
        public void ind_Chapter02_02DesDorsShape(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_02DesDorsShape", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_02DesDorsShape Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_02DesDorsShape", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_02DesDorsShape Not found"; }
        }
        public void ind_Chapter02_02DesDorsShields(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_02DesDorsShields", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_02DesDorsShields Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_02DesDorsShields", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_02DesDorsShields Not found"; }
        }
        public void ind_Chapter02_02DesDorsColor(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_02DesDorsColor", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_02DesDorsColor Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_02DesDorsColor", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_02DesDors Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_03DesFrontal(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_03DesFrontal", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_03DesFrontal Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_03DesFrontal", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_03DesFrontal Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_04DesLateral(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_04DesLateral", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_04DesLateral Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_04DesLateral", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_04DesLateral Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_05DesRear(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_05DesRear", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_05DesRear Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_05DesRear", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_05DesRear Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_06DesVentralBridge(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_06DesVentralBridge", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_06DesVentralBridge Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_06DesVentralBridge", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_06DesVentralBridge Not found"; }
        }
        public void ind_Chapter02_06DesVentralBridgeShape(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_06DesVentralBridgeShape", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_06DesVentralBridge Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_06DesVentralBridgeShape", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_06DesVentralBridgeShape Not found"; }
        }
        public void ind_Chapter02_06DesVentralBridgeShiedls(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_06DesVentralBridgeShiedls", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_06DesVentralBridge Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_06DesVentralBridgeShiedls", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_06DesVentralBridgeShiedls Not found"; }
        }
        public void ind_Chapter02_06DesVentralBridgeColor(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_06DesVentralBridgeColor", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_06DesVentralBridgeColor Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_06DesVentralBridgeColor", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_06DesVentralBridgeColor Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_06DesLateral(ref String pLngLeft, ref String pLngRight)
        {
            //Resources.Strings.ind_Chapter02_04DesLateral
            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_04DesLateral", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_04DesLateral Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_04DesLateral", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_04DesLateral Not found"; }
        }

        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_07DesHeadNeck(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_07DesHeadNeck", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_07DesHeadNeck Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_07DesHeadNeck", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_07DesHeadNeck Not found"; }
        }

        public void ind_Chapter02_07DesHeadNeckShape(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_07DesHeadNeckShape", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_07DesHeadNeckShape Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_07DesHeadNeckShape", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_07DesHeadNeckShape Not found"; }
        }

        public void ind_Chapter02_07DesHeadNeckColor(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_07DesHeadNeckColor", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_07DesHeadNeckColor Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_07DesHeadNeckColor", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_07DesHeadNeck ind_Chapter02_07DesHeadNeckColor found"; }
        }

        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_08DesLegsTail(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_08DesLegsTail", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_08DesLegsTail Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_08DesLegsTail", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_08DesLegsTail Not found"; }
        }


        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_08DesLegsTailShape(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_08DesLegsTailShape", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_08DesLegsTailShape Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_08DesLegsTailShape", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_08DesLegsTailShape Not found"; }
        }

        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_08DesLegsTailColor(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_08DesLegsTailColor", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_08DesLegsTailColor Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_08DesLegsTailColor", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_08DesLegsTailColor Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_09DesBabies(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_09DesBabies", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_09DesBabies Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_09DesBabies", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_09DesBabies Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_09DesBabiesShape(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_09DesBabiesShape", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_09DesBabiesShape Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_09DesBabiesShape", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_09DesBabiesShape Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_09DesBabiesColor(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_09DesBabiesColor", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_09DesBabiesColor Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_09DesBabiesColor", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_09DesBabies Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_10DesDimor(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_10DesDimor", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_10DesDimor Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_10DesDimor", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_10DesDimor Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_11DesDifer(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_11DesDifer", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_11DesDifer Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_11DesDifer", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_11DesDifer Not found"; }
        }

        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_12DesKeys(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_12DesKeys", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_12DesKeys Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_12DesKeys", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_12DesKeys Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------



        public void ind_Chapter02_12DesHoloty(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_12DesHoloty", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_12DesHoloty Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_12DesHoloty", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_12DesHoloty Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter02_13DesNotes(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter02_13DesNotes", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter02_13DesNotes Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter02_13DesNotes", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter02_13DesNotes Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter03_00Nat(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter03_00Nat", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter03_00Nat Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter03_00Nat", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter03_00Nat Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter03_01NatLiveStyles(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter03_01NatLiveStyles", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter03_01NatLiveStyles Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter03_01NatLiveStyles", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter03_01NatLiveStyles Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter03_02NatMediaType(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter03_02NatMediaType", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter03_02NatMediaType Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter03_02NatMediaType", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter03_02NatMediaType Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter03_03LNatFoodChain(ref String pLngLeft, ref String pLngRight) {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter03_03LNatFoodChain", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter03_03LNatFoodChain Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter03_03LNatFoodChain", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter03_03LNatFoodChain Not found"; }
        }
 
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter03_04NatBreeding(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter03_04NatBreeding", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter03_04NatBreeding Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter03_04NatBreeding", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter03_04NatBreeding Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter03_06NatProActions(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter03_06NatProActions", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter03_06NatProActions Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter03_06NatProActions", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter03_06NatProActions Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter03_05NatDanger(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter03_05NatDanger", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter03_05NatDanger Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter03_05NatDanger", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter03_05NatDanger Not found"; }
        }
 
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter03_07NatNotes(ref String pLngLeft, ref String pLngRight)
        {

            try { pLngLeft = ResourceManager.GetString("ind_Chapter03_07NatNotes", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter03_07NatNotes Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter03_07NatNotes", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter03_07NatNotes Not found"; }
        }
        
 public void ind_Chapter04_00_00_BioGeographic(ref String pLngLeft, ref String pLngRight)
        {
            string key = "ind_Chapter04_00_00_BioGeographic";
           
            try { pLngLeft = ResourceManager.GetString(key, resourceCultureLeft); }
            catch { pLngLeft = key + " Not found"; }
            try { pLngRight = ResourceManager.GetString(key, resourceCultureRight); }
            catch { pLngLeft = key+ " Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------

        public void ind_Chapter04_00_00_Geo(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter04_00_00_Geo", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter04_00_00_Geo Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter04_00_00_Geo", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter04_00_00_Geo Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        private void ind_Chapter04_01_00_GeoRng(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter04_01_00_GeoRng", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter04_01_00_GeoRng Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter04_01_00_GeoRng", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter04_01_00_GeoRng Not found"; }
        }

      
   
    //-------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter04_02RngEcoCliBioRegKey(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter04_02RngEcoCliBioRegKey", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter04_02RngEcoCliBioRegKey Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter04_02RngEcoCliBioRegKey", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter04_02RngEcoCliBioRegKey Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter04_02_01_GeoDisEco(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter04_02_01_GeoDisEco", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter04_02_01_GeoDisEco Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter04_02_01_GeoDisEco", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter04_02_01_GeoDisEco Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter04_02_02_GeoNotes(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter04_02_02_GeoNotes", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter04_02_02_GeoNotes Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter04_02_02_GeoNotes", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter04_02_02_GeoNotes Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter05_00RngEco(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter05_00RngEco", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter05_00RngEco Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter05_00RngEco", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter05_00RngEco Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter05_01RngEcoAbs(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter05_01RngEcoAbs", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter05_01RngEcoAbs Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter05_01RngEcoAbs", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter05_01RngEcoAbs Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter04_02_01_AGeoKeyBiogeographicRealms(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter04_02_01_AGeoKeyBiogeographicRealms", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter04_02_01_AGeoKeyBiogeographicRealms Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter04_02_01_AGeoKeyBiogeographicRealms", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter04_02_01_AGeoKeyBiogeographicRealms Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter05_03RngEcoCliType(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter05_03RngEcoCliType", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter05_03RngEcoCliType Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter05_03RngEcoCliType", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter05_03RngEcoCliType Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter04_04_04_xx_AGeoTableTemp(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter04_04_04_xx_AGeoTableTemp", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter04_04_04_xx_AGeoTableTemp Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter04_04_04_xx_AGeoTableTemp", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter04_04_04_xx_AGeoTableTemp Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter04_04_04_xx_GeoTableRainML(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter04_04_04_xx_GeoTableRainML", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter04_04_04_xx_GeoTableRainML Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter04_04_04_xx_GeoTableRainML", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter04_04_04_xx_GeoTableRainML Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------

        public void ind_Chapter04_04_04_xx_GeoTableSun(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter04_04_04_xx_GeoTableSun", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter04_04_04_xx_GeoTableSun Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter04_04_04_xx_GeoTableSun", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter04_04_04_xx_GeoTableSun Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter05_07RngEcoCliBioRegKey(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter05_07RngEcoCliBioRegKey", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter05_07RngEcoCliBioRegKey Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter05_07RngEcoCliBioRegKey", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter05_07RngEcoCliBioRegKey Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter06_00Car(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter06_00Car", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter06_00Car Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter06_00Car", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter06_00Car Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter06_01CarIntro(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter06_01CarIntro", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter06_01CarIntro Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter06_01CarIntro", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter06_01CarIntro Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------

        public void ind_Chapter06_02CarValues(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter06_02CarValues", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter06_02CarValues Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter06_02CarValues", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter06_02CarValues Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter06_03CarFoods(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter06_03CarFoods", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter06_03CarFoods Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter06_03CarFoods", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter06_03CarFoods Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter06_04CarBreeding(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter06_04CarBreeding", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter06_04CarBreeding Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter06_04CarBreeding", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter06_04CarBreeding Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------

        public void ind_Chapter06_05CarVivariumIndoor(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter06_05CarVivariumIndoor", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter06_05CarVivariumIndoor Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter06_05CarVivariumIndoor", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter06_05CarVivariumIndoor Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter06_06CarVivariuminOut(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter06_06CarVivariuminOut", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter06_06CarVivariuminOut Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter06_06CarVivariuminOut", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter06_06CarVivariuminOut Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter06_07CarNotes(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter06_07CarNotes", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter06_07CarNotes Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter06_07CarNotes", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter06_07CarNotes Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter06_08CarSpecialists(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter06_08CarSpecialists", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter06_08CarSpecialists Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter06_08CarSpecialists", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter06_08CarSpecialists Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter07_00Tax(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter07_00Tax", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter07_00Tax Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter07_00Tax", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter07_00Tax Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter07_00TaxIndex(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter07_00TaxIndex", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter07_00TaxIndex Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter07_00TaxIndex", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter07_00TaxIndex Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter07_01TaxGroup(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter07_01TaxGroup", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter07_01TaxGroup Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter07_01TaxGroup", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter07_01TaxGroup Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter07_02TaxSubes(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter07_02TaxSubes", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter07_02TaxSubes Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter07_02TaxSubes", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter07_02TaxSubes Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter07_03TaxEtim(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter07_03TaxEtim", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter07_03TaxEtim Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter07_03TaxEtim", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter07_03TaxEtim Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter07_04TaxSinon(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter07_04TaxSinon", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter07_04TaxSinon Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter07_04TaxSinon", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter07_04TaxSinon Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter07_05TaxVulg(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter07_05TaxVulg", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter07_05TaxVulg Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter07_05TaxVulg", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter07_05TaxVulg Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------

        public void ind_Chapter07_06TaxNote(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter07_06TaxNote", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter07_06TaxNote Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter07_06TaxNote", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter07_06TaxNote Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter08_00IdeKey(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter08_00IdeKey", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter08_00IdeKey Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter08_00IdeKey", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter08_00IdeKey Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter08_01IdeKey(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter08_01IdeKey", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter08_01IdeKey Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter08_01IdeKey", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter08_01IdeKey Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter09_00Near(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter09_00Near", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter09_00Near Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter09_00Near", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter09_00Near Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter09_01NearGenus(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter09_01NearGenus", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter09_01NearGenus Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter09_01NearGenus", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter09_01NearGenus Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter09_02NearFamily(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter09_02NearFamily", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter09_02NearFamily Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter09_02NearFamily", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter09_02NearFamily Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------

        public void ind_Chapter10_00Gal(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter10_00Gal", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter10_00Gal Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter10_00Gal", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter10_00Gal Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter11_01BibAck(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter11_01BibAck", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter11_01BibAck Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter11_01BibAck", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter11_01BibAck Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter11_02BibBib(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter11_02BibBib", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter11_02BibBib Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter11_02BibBib", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter11_02BibBib Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter11_03BibLinks(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter11_03BibLinks", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter11_03BibLinks Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter11_03BibLinks", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter11_03BibLinks Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Chapter12_00Notes(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Chapter12_00Notes", resourceCultureLeft); }
            catch { pLngLeft = "ind_Chapter12_00Notes Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Chapter12_00Notes", resourceCultureRight); }
            catch { pLngLeft = "ind_Chapter12_00Notes Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_readfularticle(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_readfularticle", resourceCultureLeft); }
            catch { pLngLeft = "ind_readfularticle Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_readfularticle", resourceCultureRight); }
            catch { pLngLeft = "ind_readfularticle Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ind_Index(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ind_Index", resourceCultureLeft); }
            catch { pLngLeft = "ind_Index Not found"; }
            try { pLngRight = ResourceManager.GetString("ind_Index", resourceCultureRight); }
            catch { pLngLeft = "ind_Index Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void ing_notChapter(ref String pLngLeft, ref String pLngRight)
        {
            try { pLngLeft = ResourceManager.GetString("ing_notChapter", resourceCultureLeft); }
            catch { pLngLeft = "ing_notChapter Not found"; }
            try { pLngRight = ResourceManager.GetString("ing_notChapter", resourceCultureRight); }
            catch { pLngLeft = "ing_notChapter Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------

        public void description(ref String pLngLeft, ref String pLngRight)
        {
            //Resources.Strings.description 
            try { pLngLeft = ResourceManager.GetString("description", resourceCultureLeft); }
            catch { pLngLeft = "ing_notChapter Not found"; }
            try { pLngRight = ResourceManager.GetString("description", resourceCultureRight); }
            catch { pLngLeft = "ing_notChapter Not found"; }
        }
       
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void geography_distribution(ref String pLngLeft, ref String pLngRight)
        {
            //Resources.Strings.habitat 
            try { pLngLeft = ResourceManager.GetString("geography_distribution", resourceCultureLeft); }
            catch { pLngLeft = "ing_notChapter Not found"; }
            try { pLngRight = ResourceManager.GetString("geography_distribution", resourceCultureRight); }
            catch { pLngLeft = "ing_notChapter Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void natural_history(ref String pLngLeft, ref String pLngRight)
        {
           //esources.Strings.natural_history
            try { pLngLeft = ResourceManager.GetString("natural_history", resourceCultureLeft); }
            catch { pLngLeft = "ing_notChapter Not found"; }
            try { pLngRight = ResourceManager.GetString("natural_history", resourceCultureRight); }
            catch { pLngLeft = "ing_notChapter Not found"; }
        }
        public void care(ref String pLngLeft, ref String pLngRight)
        {
            //Resources.Strings.care;
            try { pLngLeft = ResourceManager.GetString("care", resourceCultureLeft); }
            catch { pLngLeft = "ing_notChapter Not found"; }
            try { pLngRight = ResourceManager.GetString("care", resourceCultureRight); }
            catch { pLngLeft = "ing_notChapter Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        
        public void distribution(ref String pLngLeft, ref String pLngRight)
        {
            //Resources.Strings.description 
            try { pLngLeft = ResourceManager.GetString("distribution", resourceCultureLeft); }
            catch { pLngLeft = "ing_notChapter Not found"; }
            try { pLngRight = ResourceManager.GetString("distribution", resourceCultureRight); }
            catch { pLngLeft = "ing_notChapter Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
        public void size_centimetresLDR(ref String pLngLeft, ref String pLngRight)
        {
            //esources.Strings.natural_history
            try { pLngLeft = ResourceManager.GetString("size_centimetresLDR", resourceCultureLeft); }
            catch { pLngLeft = "ing_notChapter Not found"; }
            try { pLngRight = ResourceManager.GetString("size_centimetresLDR", resourceCultureRight); }
            catch { pLngLeft = "ing_notChapter Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
       
              public void sice_centimeters(ref String pLngLeft, ref String pLngRight)
        {
            //esources.Strings.natural_history
            try { pLngLeft = ResourceManager.GetString("sice_centimeters", resourceCultureLeft); }
            catch { pLngLeft = "ing_notChapter Not found"; }
            try { pLngRight = ResourceManager.GetString("sice_centimeters", resourceCultureRight); }
            catch { pLngLeft = "ing_notChapter Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------
       
              public void size_grames(ref String pLngLeft, ref String pLngRight)
        {
            //esources.Strings.natural_history
            try { pLngLeft = ResourceManager.GetString("size_grames", resourceCultureLeft); }
            catch { pLngLeft = "ing_notChapter Not found"; }
            try { pLngRight = ResourceManager.GetString("size_grames", resourceCultureRight); }
            catch { pLngLeft = "ing_notChapter Not found"; }
        }
        //---------------------------------------------------------------------------------
        //---------------------------------------------------------------------------------


    }
}
